'use strict';

export const Pokedex: {[k: string]: ModdedSpeciesData} = {
  	arenay: {
		num: 50001,
		name: "Arenay",
		baseForme: "Normal",
		types: ["Normal"],
		gender: "N",
		baseStats: {hp: 90, atk: 70, def: 70, spa: 70, spd: 70, spe: 70},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Arenay-Bug", "Arenay-Dark", "Arenay-Dragon", "Arenay-Electric", "Arenay-Fairy", "Arenay-Fighting", "Arenay-Fire", "Arenay-Flying", "Arenay-Ghost", "Arenay-Grass", "Arenay-Ground", "Arenay-Ice", "Arenay-Poison", "Arenay-Psychic", "Arenay-Rock", "Arenay-Steel", "Arenay-Water"],
		formeOrder: [
			"Arenay", "Arenay-Fire", "Arenay-Water", "Arenay-Grass", "Arenay-Flying", "Arenay-Steel", "Arenay-Electric", "Arenay-Ice", "Arenay-Psychic",
			"Arenay-Bug", "Arenay-Ground", "Arenay-Poison", "Arenay-Dragon", "Arenay-Fighting", "Arenay-Rock", "Arenay-Ghost", "Arenay-Dark", "Arenay-Fairy",
		],

	},
	arenayfire: {
		num: 50001,
		name: "Arenay-Fire",
		baseSpecies: "Arenay",
		forme: "Fire",
		types: ["Fire"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 60, spa: 90, spd: 60, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Fire Cellulose"],
		changesFrom: "Arenay",
	},
	arenaywater: {
		num: 50001,
		name: "Arenay-Water",
		baseSpecies: "Arenay",
		forme: "Water",
		types: ["Water"],
		gender: "N",
		baseStats: {hp: 90, atk: 60, def: 70, spa: 90, spd: 90, spe: 60},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Water Cellulose"],
		changesFrom: "Arenay",
	},
	arenaygrass: {
		num: 50001,
		name: "Arenay-Grass",
		baseSpecies: "Arenay",
		forme: "Grass",
		types: ["Grass"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 60, spa: 100, spd: 60, spe: 70},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Grass Cellulose"],
		changesFrom: "Arenay",
	},
	arenayflying: {
		num: 50001,
		name: "Arenay-Flying",
		baseSpecies: "Arenay",
		forme: "Flying",
		types: ["Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 60, spa: 90, spd: 60, spe: 100},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Flying Cellulose"],
		changesFrom: "Arenay",
	},
	arenaysteel: {
		num: 50001,
		name: "Arenay-Steel",
		baseSpecies: "Arenay",
		forme: "Steel",
		types: ["Steel"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 100, spa: 60, spd: 60, spe: 70},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Alloy Cellulose"],
		changesFrom: "Arenay",
	},
	arenayelectric: {
		num: 50001,
		name: "Arenay-Electric",
		baseSpecies: "Arenay",
		forme: "Electric",
		types: ["Electric"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 60, spa: 100, spd: 70, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Electric Cellulose"],
		changesFrom: "Arenay",
	},
	arenayice: {
		num: 50001,
		name: "Arenay-Ice",
		baseSpecies: "Arenay",
		forme: "Ice",
		types: ["Ice"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 70, spa: 90, spd: 60, spe: 100},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Ice Cellulose"],
		changesFrom: "Arenay",
	},
	arenaypsychic: {
		num: 50001,
		name: "Arenay-Psychic",
		baseSpecies: "Arenay",
		forme: "Psychic",
		types: ["Psychic"],
		gender: "N",
		baseStats: {hp: 90, atk: 70, def: 50, spa: 110, spd: 90, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Psychic Cellulose"],
		changesFrom: "Arenay",
	},
	arenaybug: {
		num: 50001,
		name: "Arenay-Bug",
		baseSpecies: "Arenay",
		forme: "Bug",
		types: ["Bug"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 60, spa: 70, spd: 90, spe: 60},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Bug Cellulose"],
		changesFrom: "Arenay",
	},
	arenayground: {
		num: 50001,
		name: "Arenay-Ground",
		baseSpecies: "Arenay",
		forme: "Ground",
		types: ["Ground"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 90, spa: 60, spd: 70, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Ground Cellulose"],
		changesFrom: "Arenay",
	},
	arenaypoison: {
		num: 50001,
		name: "Arenay-Poison",
		baseSpecies: "Arenay",
		forme: "Poison",
		types: ["Poison"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 60, spa: 100, spd: 60, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Poison Cellulose"],
		changesFrom: "Arenay",
	},
	arenaydragon: {
		num: 50001,
		name: "Arenay-Dragon",
		baseSpecies: "Arenay",
		forme: "Dragon",
		types: ["Dragon"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 50, spa: 110, spd: 90, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Dragon Cellulose"],
		changesFrom: "Arenay",
	},
	arenayfighting: {
		num: 50001,
		name: "Arenay-Fighting",
		baseSpecies: "Arenay",
		forme: "Fighting",
		types: ["Fighting"],
		gender: "N",
		baseStats: {hp: 90, atk: 120, def: 50, spa: 50, spd: 110, spe: 90},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Fighting Cellulose"],
		changesFrom: "Arenay",
	},
	arenayrock: {
		num: 50001,
		name: "Arenay-Rock",
		baseSpecies: "Arenay",
		forme: "Rock",
		types: ["Rock"],
		gender: "N",
		baseStats: {hp: 90, atk: 90, def: 120, spa: 50, spd: 80, spe: 50},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Rock Cellulose"],
		changesFrom: "Arenay",
	},
	arenayghost: {
		num: 50001,
		name: "Arenay-Ghost",
		baseSpecies: "Arenay",
		forme: "Ghost",
		types: ["Ghost"],
		gender: "N",
		baseStats: {hp: 90, atk: 80, def: 60, spa: 100, spd: 70, spe: 70},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Ghost Cellulose"],
		changesFrom: "Arenay",
	},
	arenaydark: {
		num: 50001,
		name: "Arenay-Dark",
		baseSpecies: "Arenay",
		forme: "Dark",
		types: ["Dark"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 60, spa: 100, spd: 70, spe: 70},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Dark Cellulose"],
		changesFrom: "Arenay",
	},
	arenayfairy: {
		num: 50001,
		name: "Arenay-Fairy",
		baseSpecies: "Arenay",
		forme: "Fairy",
		types: ["Fairy"],
		gender: "N",
		baseStats: {hp: 90, atk: 70, def: 50, spa: 100, spd: 120, spe: 60},
		abilities: {0: "Splice"},
		heightm: 0.3,
		weightkg: 6.5,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItems: ["Psychic Cellulose"],
		changesFrom: "Arenay",
	},
	Eevee: {
		inherit: true,
		evos: ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon", "Aeveon", "Chromeon"],
	},
	aeveon: {
		num: 50002,
		name: "Aeveon",
		types: ["Flying"],
		baseStats: {hp: 95, atk: 65, def: 110, spa: 60, spd: 130, spe: 65},
		abilities: {0: "Synchronize", H: "Inner Focus"},
		heightm: 1,
		weightkg: 27,
		color: "Black",
		prevo: "Eevee",
		evoType: "useItem",
		evoItem: "Bio Stone",
		eggGroups: ["Field"],
	},
	chromeon: {
		num: 50003,
		name: "Chromeon",
		types: ["Steel"],
		baseStats: {hp: 95, atk: 65, def: 110, spa: 60, spd: 130, spe: 65},
		abilities: {0: "Synchronize", H: "Inner Focus"},
		heightm: 1,
		weightkg: 27,
		color: "Black",
		prevo: "Eevee",
		evoType: "useItem",
		evoItem: "Mech Stone",
		eggGroups: ["Field"],
	},
